---

- name: move keys and certificates to the good place for the CA
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn
    owner: root
    group: root
    mode: '0600'
  with_items:
    - minica.pem
    - minica-key.pem

- name: move keys and certificates to the good place for the server
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn/server
    owner: root
    group: root
    mode: '0600'
  with_items:
    - cert.pem
    - key.pem

