---
- name: copy server conf file in server directory
  copy:
    src: server.conf
    dest: /etc/openvpn/server
    owner: root
    group: root
    mode: u+rw,g-r,o-r
  notify:
    - restart openvpn

- name: Ansible check takey exists
  stat:
    path: /etc/openvpn/ta.key
  register: ta_exists

- name: generate ta.key
  shell: cd /etc/openvpn && openvpn --genkey --secret ta.key
  when: ta_exists.stat.exists == False

- name: Ansible check dhkey exists
  stat:
    path: /etc/openvpn/dh2048.pem
  register: dh_exists

- name: generate dh key
  shell: cd /etc/openvpn && openssl dhparam -out dh2048.pem 2048
  when: dh_exists.stat.exists == False

- name: Configure iptables
  import_tasks: iptables.yml

- name: Configure client
  import_tasks: client.yml
  tags: create_client