---
- name: copy client conf file in client directory
  template:
    src: "server.conf.j2"
    dest: "/etc/openvpn/server/server.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart_openvpn

- name: Ansible check takey exists
  stat:
    path: /etc/openvpn/ta.key
  register: ta_exists

- name: generate ta.key
  shell: cd /etc/openvpn && openvpn --genkey --secret ta.key
  when: ta_exists.stat.exists == False

- name: Ansible check dhkey exists
  stat:
    path: /etc/openvpn/dh2048.pem
  register: dh_exists

- name: generate dh key
  shell: cd /etc/openvpn && openssl dhparam -out dh2048.pem 2048
  when: dh_exists.stat.exists == False

- name: Enable ip forward
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present

- name: Configure iptables
  import_tasks: iptables.yml

- name: Configure client
  import_tasks: client.yml
  tags: create_client

- name: OpenVPN is started and enabled
  systemd:
    name: openvpn-server@server
    state: started
    enabled: yes